### ISSUE TITLE
support for CTE used in another CTE

### ISSUE THREAD

**Issue by hayssams** [starlake-ai/jsqltranspiler#33]
The following query fails 
```
with mycte as (
  select o.amount, c.id, CURRENT_TIMESTAMP() as timestamp1, o.amount as amount2
  from sales.orders o, sales.customers c
  where o.customer_id = c.id
),
yourcte as (select * from mycte)
select id, sum(amount) as sum, timestamp1, amount as amount2
from yourcte
group by yourcte.id, yourcte.timestamp1
```

with the following message:

```
Exception in thread "main" java.lang.RuntimeException: Table mycte does not exist in the given Schema 
	at ai.starlake.transpiler.schema.JdbcMetaData.getColumn(JdbcMetaData.java:264)
	at ai.starlake.transpiler.JSQLExpressionColumnResolver.getJdbcColumn(JSQLExpressionColumnResolver.java:92)
	at ai.starlake.transpiler.JSQLExpressionColumnResolver.visit(JSQLExpressionColumnResolver.java:339)
	at ai.starlake.transpiler.JSQLExpressionColumnResolver.visit(JSQLExpressionColumnResolver.java:35)
	at net.sf.jsqlparser.schema.Column.accept(Column.java:157)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:507)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:530)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:60)
	at net.sf.jsqlparser.statement.select.PlainSelect.accept(PlainSelect.java:317)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:326)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:351)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:60)
	at net.sf.jsqlparser.statement.select.ParenthesedSelect.accept(ParenthesedSelect.java:146)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:583)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:60)
	at net.sf.jsqlparser.statement.select.WithItem.accept(WithItem.java:63)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:371)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:530)
	at ai.starlake.transpiler.JSQLColumResolver.visit(JSQLColumResolver.java:60)
	at net.sf.jsqlparser.statement.select.PlainSelect.accept(PlainSelect.java:317)
	at ai.starlake.transpiler.JSQLColumResolver.getResultSetMetaData(JSQLColumResolver.java:128)
```

**Comment by hayssams** [comment]
Gr8 !
Thank you !
